"use client";
import {useCallback,useEffect,useState} from "react";
import {NetworkOnboarding} from "@/components/NetworkOnboarding";
type R={id:string;support_options:string[];status:string;location_label:string|null;partner_response:string|null;requester_update:string|null;created_at:string};
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase());
export function FacilityReviewWorkspace(){const[rows,setRows]=useState<R[]>([]),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState("Loading facility activity..."),[onboard,setOnboard]=useState(false);
const load=useCallback(async()=>{const r=await fetch("/api/facility-requests",{cache:"no-store"});if(r.status===401){location.assign("/facility-login");return;}const b=await r.json().catch(()=>null);if(r.status===403&&b?.code==="onboarding-required"){setOnboard(true);return;}if(!r.ok||!Array.isArray(b)){setMessage(b?.message??"Unable to load facility activity.");return;}setRows(b);setSelected(x=>x&&b.some((y:R)=>y.id===x)?x:b[0]?.id??null);setMessage(b.length?"Facility is informed automatically. No approval is required.":"No spiritual-care requests yet.");},[]);
useEffect(()=>{void load()},[load]);const row=rows.find(x=>x.id===selected)??null;
async function signOut(){await fetch("/api/facility-requests",{method:"DELETE"});location.assign("/facility-login");}
if(onboard)return <main className="min-h-screen bg-[#edf4f0] p-6"><div className="mx-auto max-w-3xl"><NetworkOnboarding role="facility"/></div></main>;
return <main className="min-h-screen bg-[#edf4f0] p-6 text-[#0d2b3b]"><div className="mx-auto max-w-6xl"><header className="rounded-[2rem] border bg-white p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#19726c]">ChurchWork · Facility portal</p><h1 className="mt-2 font-serif text-4xl font-semibold">Spiritual-care activity</h1><p className="mt-2 text-sm font-semibold text-[#4f6259]">{message}</p></div><button onClick={signOut} className="rounded-xl border px-4 py-3 text-sm font-black">Sign out</button></div></header><div className="mt-6 grid gap-6 lg:grid-cols-[22rem_1fr]"><aside className="rounded-[1.5rem] border bg-white p-4">{rows.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`mb-2 w-full rounded-xl border p-4 text-left ${selected===r.id?"border-[#19726c] bg-[#e4f3f1]":""}`}><strong>{r.location_label||"Facility location"}</strong><span className="block text-xs">{r.support_options.join(", ")} · {pretty(r.status)}</span></button>)}</aside><section className="rounded-[1.5rem] border bg-white p-6">{row?<><p className="text-xs font-black uppercase text-[#506a49]">Location</p><h2 className="mt-2 font-serif text-3xl font-semibold">{row.location_label||"Facility location"}</h2><p className="mt-4 text-lg font-black">{row.support_options.join(", ")}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f8fbf8] p-4"><p className="text-xs font-black uppercase">Request status</p><p className="mt-2 font-bold">{pretty(row.status)}</p></div><div className="rounded-xl bg-[#f8fbf8] p-4"><p className="text-xs font-black uppercase">Partner response</p><p className="mt-2 font-bold">{row.partner_response?pretty(row.partner_response):"Awaiting response"}</p></div></div><p className="mt-6 rounded-xl bg-[#e7f1eb] p-4 text-sm font-bold text-[#0f6b54]">No facility action is required. This view keeps your team aware of incoming requests and partner activity.</p></>:<p>No request selected.</p>}</section></div></div></main>}