"use client";
import {useEffect,useMemo,useState} from "react";
type Choice={facility_id:string;facility_name:string;city?:string|null;state?:string|null;partners:{partner_id:string;partner_name:string}[]};
type Row={id:string;support:string[];status:string;location_label:string;requester_update?:string|null;created_at:string};
const options=["Prayer","Friendly visit","Encouragement","Pastoral call"];
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export function GuestRequestWorkspace(){
 const[choices,setChoices]=useState<Choice[]>([]),[rows,setRows]=useState<Row[]>([]),[facility,setFacility]=useState(""),[partner,setPartner]=useState(""),[location,setLocation]=useState(""),[support,setSupport]=useState<string[]>([]),[msg,setMsg]=useState("Loading available care partners..."),[busy,setBusy]=useState(false),[locationId,setLocationId]=useState("");
 const selected=useMemo(()=>choices.find(x=>x.facility_id===facility),[choices,facility]);
 async function load(){const code=new URLSearchParams(location.search).get("location");const r=await fetch(`/api/guest-requests${code?`?location=${encodeURIComponent(code)}`:""}`,{cache:"no-store"});const b=await r.json().catch(()=>null);if(!r.ok||!b?.ok){setMsg("Request service is unavailable.");return;}setChoices(Array.isArray(b.choices)?b.choices:[]);setRows(Array.isArray(b.requests)?b.requests:[]);if(b.resolvedLocation?.facility_id){setFacility(b.resolvedLocation.facility_id);setLocation(b.resolvedLocation.location_label??"");setLocationId(b.resolvedLocation.location_id??"");}setMsg("");}
 useEffect(()=>{void load()},[]);
 function toggle(v:string){setSupport(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);}
 async function submit(){if(!facility||!partner||!location.trim()||!support.length||busy)return;setBusy(true);const r=await fetch("/api/guest-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({facilityId:facility,partnerId:partner,locationLabel:location,locationId:locationId||undefined,support})});const b=await r.json().catch(()=>null);setMsg(b?.message??"Request did not complete.");if(r.ok){setSupport([]);await load();}setBusy(false);}
 async function newGuest(){await fetch("/api/guest-requests",{method:"DELETE"});setRows([]);setSupport([]);setMsg("A new private guest session has started.");}
 return <main className="min-h-screen bg-[#edf4f0] p-5 text-[#0d2b3b]"><div className="mx-auto max-w-4xl">
 <header className="rounded-[2rem] bg-[#082838] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-[#8dbd9e]">ChurchWork guest request</p><h1 className="mt-2 font-serif text-4xl font-semibold">Request spiritual care without creating an account.</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-[#d9e7df]">ChurchWork does not ask for your name, diagnosis, medical information, or a written message. Choose only from the options below.</p></header>
 <section className="mt-5 rounded-[1.5rem] border bg-white p-6"><div className="grid gap-4 md:grid-cols-3">
 <label className="text-sm font-black">Facility<select value={facility} onChange={e=>{setFacility(e.target.value);setPartner("");}} className="mt-2 w-full rounded-xl border p-3"><option value="">Choose facility</option>{choices.map(x=><option key={x.facility_id} value={x.facility_id}>{x.facility_name}</option>)}</select></label>
 <label className="text-sm font-black">Room / location<input value={location} readOnly={!!locationId} onChange={e=>setLocation(e.target.value)} placeholder="Room 406" maxLength={80} className="mt-2 w-full rounded-xl border p-3 read-only:bg-[#edf4f0]"/></label>
 <label className="text-sm font-black">Care partner<select value={partner} disabled={!selected} onChange={e=>setPartner(e.target.value)} className="mt-2 w-full rounded-xl border p-3 disabled:opacity-50"><option value="">Choose partner</option>{(selected?.partners??[]).map(x=><option key={x.partner_id} value={x.partner_id}>{x.partner_name}</option>)}</select></label>
 </div><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-[#506a49]">What would help?</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{options.map(v=><button key={v} onClick={()=>toggle(v)} className={`rounded-xl border p-4 text-left font-black ${support.includes(v)?"border-[#0f6b54] bg-[#e7f1eb]":"bg-[#f8fbf8]"}`}>{support.includes(v)?"✓ ":""}{v}</button>)}</div>
 <button disabled={busy||!facility||!partner||!location.trim()||!support.length} onClick={submit} className="mt-6 w-full rounded-xl bg-[#0f3f35] px-5 py-4 font-black text-white disabled:opacity-40">{busy?"Sending...":"Send request"}</button>{msg?<p className="mt-4 rounded-xl bg-[#f8fbf8] p-4 text-sm font-bold">{msg}</p>:null}</section>
 <section className="mt-5 rounded-[1.5rem] border bg-white p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#506a49]">This guest session</p><h2 className="mt-1 font-serif text-2xl font-semibold">Request status</h2></div><button onClick={newGuest} className="rounded-xl border px-3 py-2 text-xs font-black">New person / new visit</button></div><div className="mt-4 space-y-3">{rows.length?rows.map(r=><div key={r.id} className="rounded-xl bg-[#f8fbf8] p-4"><div className="flex justify-between gap-3"><strong>{r.support.join(", ")}</strong><span className="text-xs font-black">{pretty(r.status)}</span></div><p className="mt-1 text-xs font-bold text-[#63736b]">{r.location_label}</p>{r.requester_update?<p className="mt-3 text-sm font-bold text-[#0f6b54]">{r.requester_update}</p>:null}</div>):<p className="text-sm font-semibold text-[#63736b]">No requests in this guest session.</p>}</div></section>
 </div></main>;
}