"use client";
import {useEffect,useState} from "react";
import {NetworkOnboarding} from "@/components/NetworkOnboarding";
import {PartnerCoverage} from "@/components/PartnerCoverage";
type R={id:string;support_options:string[];status:string;location_label:string|null;partner_response:string|null};
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export function PartnerWorkspace(){const[rows,setRows]=useState<R[]>([]),[sel,setSel]=useState<R|null>(null),[msg,setMsg]=useState("Loading requests..."),[busy,setBusy]=useState(false),[needsOnboarding,setNeedsOnboarding]=useState(false);
async function load(){const r=await fetch("/api/partner-requests",{cache:"no-store"});if(r.status===401){location.assign("/partner-login");return;}const b=await r.json().catch(()=>null);if(r.status===403&&b?.code==="onboarding-required"){setNeedsOnboarding(true);setMsg("");return;}if(!r.ok||!Array.isArray(b)){setMsg(b?.message??"Requests could not be loaded.");return;}setRows(b);setSel(x=>b.find((y:R)=>y.id===x?.id)??b[0]??null);setMsg(b.length?"":"No requests are waiting.");}
useEffect(()=>{void load()},[]);
async function act(outcome:string){if(!sel||busy)return;setBusy(true);const r=await fetch("/api/partner-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:sel.id,outcome})});const b=await r.json().catch(()=>null);setMsg(r.ok?"Request status updated.":b?.message??"Response could not be recorded.");await load();setBusy(false);}
async function signOut(){await fetch("/api/partner-requests",{method:"DELETE"});location.assign("/partner-login");}
if(needsOnboarding)return <main className="min-h-screen bg-[#edf4f0] p-6"><div className="mx-auto max-w-3xl"><NetworkOnboarding role="partner"/></div></main>;
return <main className="min-h-screen bg-[#edf4f0] p-6 text-[#0d2b3b]"><section className="mx-auto max-w-6xl"><header className="rounded-[2rem] border bg-white p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#506a49]">ChurchWork · Partner portal</p><h1 className="mt-2 font-serif text-4xl font-semibold">Spiritual-care requests</h1><p className="mt-2 text-sm">{msg}</p></div><button onClick={signOut} className="rounded-xl border px-4 py-3 text-sm font-black">Sign out</button></div></header><PartnerCoverage/><div className="mt-6 grid gap-6 md:grid-cols-[20rem_1fr]"><aside className="rounded-[1.5rem] border bg-white p-4">{rows.map(r=><button key={r.id} onClick={()=>setSel(r)} className={`mb-2 w-full rounded-xl border p-4 text-left ${sel?.id===r.id?"border-[#0f6b54] bg-[#e7f1eb]":""}`}><strong>{r.location_label||"Facility location"}</strong><span className="block text-xs">{r.support_options.join(", ")} · {label(r.status)}</span></button>)}</aside><section className="rounded-[1.5rem] border bg-white p-6">{!sel?<p>No request selected.</p>:<><p className="text-xs font-black uppercase">Location</p><h2 className="mt-2 font-serif text-3xl font-semibold">{sel.location_label||"Facility location"}</h2><p className="mt-4 text-lg font-black">{sel.support_options.join(", ")}</p><p className="mt-2 text-sm font-bold">Status: {label(sel.status)}</p>{sel.status==="submitted"?<div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={busy} onClick={()=>act("accepted")} className="rounded-xl bg-[#0f3f35] px-4 py-3 text-sm font-black text-white">Accept request</button><button disabled={busy} onClick={()=>act("declined")} className="rounded-xl border px-4 py-3 text-sm font-black">Decline request</button></div>:null}{sel.status==="accepted_by_partner"?<button disabled={busy} onClick={()=>act("visit_planned")} className="mt-6 rounded-xl bg-[#0f3f35] px-4 py-3 text-sm font-black text-white">Plan visit</button>:null}{sel.status==="visit_planned"?<button disabled={busy} onClick={()=>act("completed")} className="mt-6 rounded-xl bg-[#0f3f35] px-4 py-3 text-sm font-black text-white">Mark completed</button>:null}</>}</section></div></section></main>}