"use client";
import {useEffect,useState} from "react";
import { NetworkOnboarding } from "@/components/NetworkOnboarding";
import { PartnerCoverage } from "@/components/PartnerCoverage";
type R={id:string;support_options:string[];safe_context_note:string;status:string;partner_outcome:string|null};
const outcomes=[["prayer_logged","Prayer logged"],["visit_planned","Visit planned"],["visit_completed","Visit completed"],["follow_up_requested","Follow-up requested"]] as const;
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export function PartnerWorkspace(){const[rows,setRows]=useState<R[]>([]),[sel,setSel]=useState<R|null>(null),[msg,setMsg]=useState("Loading approved assignments..."),[busy,setBusy]=useState(false),[needsOnboarding,setNeedsOnboarding]=useState(false);
async function load(){const r=await fetch("/api/partner-requests",{cache:"no-store"});if(r.status===401){location.assign("/partner-login");return;}const b=await r.json().catch(()=>null);if(r.status===403&&b?.code==="onboarding-required"){setNeedsOnboarding(true);setMsg("");return;}if(!r.ok||!Array.isArray(b)){setMsg(b?.message??"Partner assignments could not be loaded.");return;}setRows(b);setSel(c=>b.find((x:R)=>x.id===c?.id)??b[0]??null);setMsg(b.length?"Approved assignments loaded.":"No approved assignments are waiting.");}
useEffect(()=>{void load()},[]);
async function record(outcome:string){if(!sel||busy)return;setBusy(true);const r=await fetch("/api/partner-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:sel.id,outcome})});const b=await r.json().catch(()=>null);if(!r.ok){setMsg(b?.message??"Outcome could not be recorded.");setBusy(false);return;}setMsg("Partner outcome recorded for facility review.");await load();setBusy(false);}
async function signOut(){await fetch("/api/partner-requests",{method:"DELETE"});location.assign("/partner-login");}
if(needsOnboarding)return <main className="min-h-screen bg-[#edf4f0] p-6"><div className="mx-auto max-w-3xl"><NetworkOnboarding role="partner" /></div></main>;
return <main className="min-h-screen bg-[#edf4f0] p-6 text-[#0d2b3b]"><section className="mx-auto max-w-6xl"><header className="rounded-[2rem] border border-[#d9dfd7] bg-white p-7 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#506a49]">ChurchWork · Partner portal</p><h1 className="mt-2 font-serif text-4xl font-semibold">Approved care assignments</h1><p className="mt-2 text-sm">{msg}</p></div><button onClick={signOut} className="rounded-xl border px-4 py-3 text-sm font-black">Sign out</button></div></header><PartnerCoverage /><div className="mt-6 grid gap-6 md:grid-cols-[20rem_1fr]"><aside className="rounded-[1.5rem] border bg-white p-4"><p className="mb-3 text-xs font-black uppercase">Assignments</p>{rows.map(r=><button key={r.id} onClick={()=>setSel(r)} className={`mb-2 w-full rounded-xl border p-4 text-left ${sel?.id===r.id?"border-[#0f6b54] bg-[#e7f1eb]":""}`}><strong>{r.support_options.join(", ")}</strong><span className="block text-xs">{label(r.status)}</span></button>)}</aside><section className="rounded-[1.5rem] border bg-white p-6">{!sel?<p>No approved assignment selected.</p>:<><p className="text-xs font-black uppercase">Approved spiritual-care context</p><h2 className="mt-2 font-serif text-3xl font-semibold">{sel.support_options.join(", ")}</h2><div className="mt-5 rounded-2xl bg-[#f8fbf8] p-5">{sel.safe_context_note}</div><p className="mt-4 text-sm font-bold">Status: {label(sel.status)}</p>{sel.status==="approved_for_partner"?<div className="mt-6 grid gap-3 sm:grid-cols-2">{outcomes.map(([v,t])=><button disabled={busy} key={v} onClick={()=>record(v)} className="rounded-xl bg-[#0f3f35] px-4 py-3 text-sm font-black text-white disabled:opacity-50">{t}</button>)}</div>:<div className="mt-6 rounded-xl bg-[#e7f1eb] p-4 text-sm font-bold">Outcome recorded: {sel.partner_outcome?label(sel.partner_outcome):"Complete"}</div>}</>}</section></div></section></main>}
