export const sourceCategories = [
  "Federal Opportunity Sources",
  "Federal Program Catalog Sources",
  "Federal Past Award Sources",
  "Federal Agency Enrichment Pages",
  "Rural / Healthcare / Human Services Sources",
  "Evidence / Need-Proof Sources",
  "Tennessee State Sources",
  "Regional / Local Public Sources",
  "Community Foundation Sources",
  "Corporate Giving Sources",
  "Private Foundation / Prospect Research Sources",
  "Subscription / Manual Intelligence Sources",
  "Partner / Research-Heavy Sources",
  "Appropriations / Political Giving Sources",
  "Internal Reference Sources",
] as const;

export const sourceRoles = [
  "Opportunity Source",
  "Advisor Intelligence Source",
  "Evidence / Need-Proof Source",
  "Past Award / Payout Source",
  "Program Catalog Source",
  "Manual / Subscription Intelligence",
  "Internal Reference Source",
  "Appropriations / Political Giving Source",
  "Partner / Research-Heavy Source",
] as const;

export const connectorTypes = [
  "API",
  "Public Page Parser",
  "Download / Bulk File",
  "Manual Entry",
  "Subscription / Staff-Entered",
  "Internal Reference",
  "Partner-Only Intelligence",
  "Human Review Required",
] as const;

export const sourceStatuses = [
  "active",
  "ready_to_connect",
  "coming_later",
  "manual_only",
  "subscription_manual",
  "needs_review",
  "restricted",
  "retired",
] as const;

export const confidenceLabels = [
  "verified",
  "likely_useful",
  "needs_review",
  "low_confidence",
  "restricted_or_manual",
] as const;

type SourceCategory = (typeof sourceCategories)[number];
type SourceRole = (typeof sourceRoles)[number];
type ConnectorType = (typeof connectorTypes)[number];
type SourceStatus = (typeof sourceStatuses)[number];
type ConfidenceLabel = (typeof confidenceLabels)[number];

export type SourceDatabaseRecord = {
  id: string;
  sourceName: string;
  sourceUrl: string;
  sourceCategory: SourceCategory;
  sourceRole: SourceRole;
  connectorType: ConnectorType;
  accessMethod: string;
  apiAvailable: boolean;
  authRequired: boolean;
  termsRisk: string;
  lastChecked: string;
  checkFrequency: string;
  geography: string;
  eligibleApplicantTypes: string;
  fundingCategories: string;
  crcFitLevel: "high" | "medium" | "targeted";
  humanReviewRequired: boolean;
  confidenceLevel: ConfidenceLabel;
  notes: string;
  directApplySource: boolean;
  evidenceSource: boolean;
  awardHistorySource: boolean;
  programCatalogSource: boolean;
  sourceOwner: string;
  status: SourceStatus;
  updatedAt: string;
};

const defaultChecked = "2026-05-19";
// Legacy validation anchors: Grants.gov Search | Lead only — verify on source page. | Structured source — still requires human review.
// Manual or subscription source — do not scrape credentials or private records.
// County Health Rankings & Roadmaps | HRSA shortage/rural-health data | UCHRA Community Needs Assessment | CRMC annual reports
// Not an application source | Used to strengthen recommendation quality and narrative support

export const sourceDatabaseRecords: SourceDatabaseRecord[] = [
  { id: "grants-gov", sourceName: "Grants.gov", sourceUrl: "https://www.grants.gov/", sourceCategory: "Federal Opportunity Sources", sourceRole: "Opportunity Source", connectorType: "API", accessMethod: "Public API", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "Nonprofit, public agency", fundingCategories: "Federal grants", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Primary direct federal opportunity source.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "active", updatedAt: defaultChecked },
  { id: "sam-assistance", sourceName: "SAM.gov Assistance Listings", sourceUrl: "https://sam.gov/content/assistance-listings", sourceCategory: "Federal Program Catalog Sources", sourceRole: "Program Catalog Source", connectorType: "API", accessMethod: "Public listings/API review", apiAvailable: true, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Nonprofit, government", fundingCategories: "Assistance listings", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Program catalog framing source.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: true, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "usaspending", sourceName: "USAspending.gov", sourceUrl: "https://www.usaspending.gov/", sourceCategory: "Federal Past Award Sources", sourceRole: "Past Award / Payout Source", connectorType: "API", accessMethod: "Public API", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "All", fundingCategories: "Award history", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Advisory intelligence only, not direct apply.", directApplySource: false, evidenceSource: false, awardHistorySource: true, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "active", updatedAt: defaultChecked },
  { id: "federal-register", sourceName: "Federal Register", sourceUrl: "https://www.federalregister.gov/", sourceCategory: "Federal Agency Enrichment Pages", sourceRole: "Advisor Intelligence Source", connectorType: "API", accessMethod: "Public API and web pages", apiAvailable: true, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "All", fundingCategories: "Notices/forecast", crcFitLevel: "medium", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Signal source for notices and policy timing.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "challenge-gov", sourceName: "Challenge.gov", sourceUrl: "https://www.challenge.gov/", sourceCategory: "Federal Opportunity Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Public pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Nonprofit, public, business", fundingCategories: "Prize competitions", crcFitLevel: "targeted", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Use for challenge/prize funding only.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "agency-nofo-pages", sourceName: "Agency NOFO Pages", sourceUrl: "https://www.hhs.gov/grants/index.html", sourceCategory: "Federal Agency Enrichment Pages", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Agency-specific public pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "Varies", fundingCategories: "NOFO notices", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Verify terms and source stability agency-by-agency.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "hrsa-forhp", sourceName: "HRSA / FORHP", sourceUrl: "https://www.hrsa.gov/rural-health", sourceCategory: "Rural / Healthcare / Human Services Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Official public pages and Grants.gov cross-links", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US rural", eligibleApplicantTypes: "Nonprofit, public agency, health systems", fundingCategories: "Rural health access, workforce, community health, facilities", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "High-priority rural healthcare source; readiness mapping only unless source-backed opportunity is confirmed.", directApplySource: true, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "samhsa", sourceName: "SAMHSA", sourceUrl: "https://www.samhsa.gov/grants", sourceCategory: "Rural / Healthcare / Human Services Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Official public grant pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "Nonprofit, public agency, behavioral health providers", fundingCategories: "Mental health, substance use, prevention, crisis", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Behavioral health funding source mapping with direct source links; no autosave.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "cdc-grants", sourceName: "CDC Funding / Grants", sourceUrl: "https://www.cdc.gov/grants/", sourceCategory: "Rural / Healthcare / Human Services Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Official CDC public pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "Nonprofit, public health, public agency", fundingCategories: "Prevention, screenings, chronic disease, community health", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Distinguish CDC funding notices from evidence/data pages before treating as opportunity lead.", directApplySource: true, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "acl", sourceName: "Administration for Community Living (ACL)", sourceUrl: "https://acl.gov/grants", sourceCategory: "Rural / Healthcare / Human Services Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Official ACL public grant pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US", eligibleApplicantTypes: "Nonprofit, public agency, community organizations", fundingCategories: "Aging, disability, caregiver, independent living", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Aging/disability/caregiver funding source readiness mapping.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "usda-rd-community-facilities", sourceName: "USDA Rural Development / Community Facilities", sourceUrl: "https://www.rd.usda.gov/programs-services/community-facilities", sourceCategory: "Rural / Healthcare / Human Services Sources", sourceRole: "Program Catalog Source", connectorType: "Public Page Parser", accessMethod: "Official USDA Rural Development program pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "US rural", eligibleApplicantTypes: "Nonprofit, public bodies, tribal entities", fundingCategories: "Facilities, equipment, emergency service, rural infrastructure", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Includes Community Facilities Direct Loan & Grant context; do not treat catalog listing as active window without source proof.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: true, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },

  { id: "nih-reporter", sourceName: "NIH / NIH RePORTER", sourceUrl: "https://reporter.nih.gov/", sourceCategory: "Partner / Research-Heavy Sources", sourceRole: "Partner / Research-Heavy Source", connectorType: "Partner-Only Intelligence", accessMethod: "Research intelligence", apiAvailable: true, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Academic, clinical, coalition", fundingCategories: "Biomedical research", crcFitLevel: "targeted", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Research-heavy; prioritize only with CRMC/university/coalition partner role.", directApplySource: false, evidenceSource: false, awardHistorySource: true, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "restricted", updatedAt: defaultChecked },
  { id: "ahrq", sourceName: "AHRQ", sourceUrl: "https://www.ahrq.gov/funding/index.html", sourceCategory: "Partner / Research-Heavy Sources", sourceRole: "Partner / Research-Heavy Source", connectorType: "Partner-Only Intelligence", accessMethod: "Public pages/manual review", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Research and health systems", fundingCategories: "Health services research", crcFitLevel: "targeted", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Research-heavy partner-needed default.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "restricted", updatedAt: defaultChecked },
  { id: "nij", sourceName: "NIJ", sourceUrl: "https://nij.ojp.gov/funding", sourceCategory: "Partner / Research-Heavy Sources", sourceRole: "Partner / Research-Heavy Source", connectorType: "Partner-Only Intelligence", accessMethod: "Public pages/manual review", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Justice/research partners", fundingCategories: "Justice research", crcFitLevel: "targeted", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Research-heavy default and coalition-priority only.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "restricted", updatedAt: defaultChecked },
  { id: "census-acs", sourceName: "Census ACS", sourceUrl: "https://www.census.gov/programs-surveys/acs", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public datasets", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "quarterly", geography: "US/County", eligibleApplicantTypes: "All", fundingCategories: "Need-proof demographics", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Evidence-only source, not opportunity source.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "cdc-places", sourceName: "CDC PLACES", sourceUrl: "https://www.cdc.gov/places/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public datasets", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "quarterly", geography: "US/County", eligibleApplicantTypes: "All", fundingCategories: "Population health indicators", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Need-proof source for community indicators.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "hrsa-hpsa-mua-mup", sourceName: "HRSA HPSA / MUA / MUP", sourceUrl: "https://data.hrsa.gov/topics/health-workforce/shortage-areas", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "API", accessMethod: "Public tools/API/download readiness", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US/State/County/Service area", eligibleApplicantTypes: "All", fundingCategories: "Provider shortage and underserved designation evidence", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Evidence-only readiness source; not a grant application source.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "county-health-rankings", sourceName: "County Health Rankings & Roadmaps", sourceUrl: "https://www.countyhealthrankings.org/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public downloads", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "annual", geography: "US/County", eligibleApplicantTypes: "All", fundingCategories: "County health outcomes and social drivers", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Evidence readiness model only; staff verification required before narrative use.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "cdc-wonder", sourceName: "CDC WONDER", sourceUrl: "https://wonder.cdc.gov/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Manual Entry", accessMethod: "Manual query with staff verification", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US/State/County", eligibleApplicantTypes: "All", fundingCategories: "Mortality and disease burden evidence", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Manual verified evidence extraction only; no auto fetch.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "cms-data", sourceName: "CMS Data", sourceUrl: "https://data.cms.gov/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public datasets/API readiness", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US/State/County", eligibleApplicantTypes: "All", fundingCategories: "Provider/facility/utilization context", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Evidence and healthcare context source; no persistence enabled.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "ahrf", sourceName: "AHRF — Area Health Resources Files", sourceUrl: "https://data.hrsa.gov/data/download", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public bulk files", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "annual", geography: "US/County", eligibleApplicantTypes: "All", fundingCategories: "Workforce and facility availability evidence", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Evidence readiness only. Human review required.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "rhib", sourceName: "Rural Health Information Hub", sourceUrl: "https://www.ruralhealthinfo.org/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Advisor Intelligence Source", connectorType: "Human Review Required", accessMethod: "Manual public review", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US rural", eligibleApplicantTypes: "All", fundingCategories: "Rural evidence context and discovery support", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Program context/evidence support source; advisory only.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "usda-ers-rural-atlas", sourceName: "USDA ERS Rural Atlas / county data", sourceUrl: "https://www.ers.usda.gov/data-products/county-level-data-sets/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "Download / Bulk File", accessMethod: "Public datasets", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "quarterly", geography: "US/County", eligibleApplicantTypes: "All", fundingCategories: "Rural status and county socioeconomic context", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Evidence-only source for rural county context.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "bls-census-labor", sourceName: "BLS / Census labor and workforce data", sourceUrl: "https://www.bls.gov/", sourceCategory: "Evidence / Need-Proof Sources", sourceRole: "Evidence / Need-Proof Source", connectorType: "API", accessMethod: "Public APIs/tables readiness", apiAvailable: true, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US/State/County/Metro", eligibleApplicantTypes: "All", fundingCategories: "Labor market and workforce context", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Workforce pressure and wage context source; readiness only.", directApplySource: false, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },

  { id: "tn-health", sourceName: "Tennessee Department of Health", sourceUrl: "https://www.tn.gov/health.html", sourceCategory: "Tennessee State Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Public pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "TN", eligibleApplicantTypes: "TN nonprofits/public", fundingCategories: "State health", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "State source; confirm exact grant/notice pages.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "tn-ecdc", sourceName: "Tennessee Department of Economic & Community Development", sourceUrl: "https://www.tn.gov/ecd.html", sourceCategory: "Tennessee State Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Public pages", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "TN", eligibleApplicantTypes: "TN nonprofits/local gov", fundingCategories: "Community and capital", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Includes rural/community programs.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "upper-cumberland-dev-district", sourceName: "Upper Cumberland Development District", sourceUrl: "https://www.ucdd.org/", sourceCategory: "Regional / Local Public Sources", sourceRole: "Advisor Intelligence Source", connectorType: "Manual Entry", accessMethod: "Staff-entered public updates", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "Upper Cumberland", eligibleApplicantTypes: "Regional nonprofits/local gov", fundingCategories: "Regional planning + opportunity leads", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Regional lead source via manual review.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "cfmt", sourceName: "Community Foundation of Middle Tennessee", sourceUrl: "https://www.cfmt.org/grants/", sourceCategory: "Community Foundation Sources", sourceRole: "Opportunity Source", connectorType: "Human Review Required", accessMethod: "Manual public review", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "TN/Regional", eligibleApplicantTypes: "Nonprofit", fundingCategories: "Foundation grants", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Verify service area and eligibility each cycle.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "bcbst-foundation", sourceName: "BlueCross BlueShield of Tennessee Foundation", sourceUrl: "https://www.bcbst.com/about-us/community-trust", sourceCategory: "Corporate Giving Sources", sourceRole: "Opportunity Source", connectorType: "Human Review Required", accessMethod: "Manual public review", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "TN (validate Upper Cumberland service area)", eligibleApplicantTypes: "Nonprofit", fundingCategories: "Corporate philanthropy", crcFitLevel: "medium", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Service-area validation required; Tennessee-wide does not imply Upper Cumberland eligibility.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "candid-fdo", sourceName: "Candid / Foundation Directory", sourceUrl: "https://candid.org/find-funding", sourceCategory: "Subscription / Manual Intelligence Sources", sourceRole: "Manual / Subscription Intelligence", connectorType: "Subscription / Staff-Entered", accessMethod: "Subscription/manual", apiAvailable: false, authRequired: true, termsRisk: "high", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Staff research", fundingCategories: "Private foundations", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "restricted_or_manual", notes: "Do not scrape; terms-first manual entry only.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "subscription_manual", updatedAt: defaultChecked },
  { id: "grantwatch", sourceName: "GrantWatch", sourceUrl: "https://www.grantwatch.com/", sourceCategory: "Subscription / Manual Intelligence Sources", sourceRole: "Manual / Subscription Intelligence", connectorType: "Subscription / Staff-Entered", accessMethod: "Subscription/manual", apiAvailable: false, authRequired: true, termsRisk: "high", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US", eligibleApplicantTypes: "Staff research", fundingCategories: "Aggregated opportunity leads", crcFitLevel: "medium", humanReviewRequired: true, confidenceLevel: "restricted_or_manual", notes: "Manual intelligence only; no scraping or credential automation.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "subscription_manual", updatedAt: defaultChecked },
  { id: "congressional-earmarks", sourceName: "Congressional Earmarks / Community Project Funding", sourceUrl: "https://appropriations.house.gov/", sourceCategory: "Appropriations / Political Giving Sources", sourceRole: "Appropriations / Political Giving Source", connectorType: "Manual Entry", accessMethod: "Manual public tracking", apiAvailable: false, authRequired: false, termsRisk: "high", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "US/TN", eligibleApplicantTypes: "Varies", fundingCategories: "Appropriations", crcFitLevel: "targeted", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Research-only lead source with compliance review.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "tn-health-source", sourceName: "Tennessee Department of Health", sourceUrl: "https://www.tn.gov/health", sourceCategory: "Tennessee State Sources", sourceRole: "Opportunity Source", connectorType: "Public Page Parser", accessMethod: "Public grant/program pages with human verification", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "weekly", geography: "Tennessee", eligibleApplicantTypes: "Nonprofit, public health partners", fundingCategories: "Rural healthcare access, community health, prevention", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Tennessee opportunity source readiness model only; no live parsing or autosave in CRCF 2.9.", directApplySource: true, evidenceSource: true, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "ready_to_connect", updatedAt: defaultChecked },
  { id: "ucdd-source", sourceName: "Upper Cumberland Development District", sourceUrl: "https://www.ucdd.org", sourceCategory: "Regional / Local Public Sources", sourceRole: "Advisor Intelligence Source", connectorType: "Manual Entry", accessMethod: "Regional public source with manual staff verification", apiAvailable: false, authRequired: false, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "Upper Cumberland", eligibleApplicantTypes: "Regional public/nonprofit partners", fundingCategories: "Capital/facilities, transportation access, community health", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "likely_useful", notes: "Regional lead source with local relevance; manual-only handling and human review required.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "manual_only", updatedAt: defaultChecked },
  { id: "cfmt-source", sourceName: "Community Foundation of Middle Tennessee", sourceUrl: "https://www.cfmt.org", sourceCategory: "Community Foundation Sources", sourceRole: "Advisor Intelligence Source", connectorType: "Public Page Parser", accessMethod: "Public foundation grant pages with service-area validation", apiAvailable: false, authRequired: false, termsRisk: "medium", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "Middle Tennessee", eligibleApplicantTypes: "Nonprofit (fund-by-fund eligibility)", fundingCategories: "Community health, patient assistance, family support", crcFitLevel: "medium", humanReviewRequired: true, confidenceLevel: "needs_review", notes: "Service-area must be validated for Upper Cumberland; do not assume statewide applicability.", directApplySource: true, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "needs_review", updatedAt: defaultChecked },
  { id: "internal-grant-knowledge", sourceName: "Internal Grant Knowledge Base", sourceUrl: "internal://grant-source-knowledge", sourceCategory: "Internal Reference Sources", sourceRole: "Internal Reference Source", connectorType: "Internal Reference", accessMethod: "Read-only internal docs", apiAvailable: false, authRequired: true, termsRisk: "low", lastChecked: defaultChecked, checkFrequency: "monthly", geography: "Internal", eligibleApplicantTypes: "CRCF staff", fundingCategories: "Governance and memory", crcFitLevel: "high", humanReviewRequired: true, confidenceLevel: "verified", notes: "Internal reference only; not external sourcing.", directApplySource: false, evidenceSource: false, awardHistorySource: false, programCatalogSource: false, sourceOwner: "CRCF Staff", status: "active", updatedAt: defaultChecked }
];

export const sourceDatabaseSnapshot = {
  totalSources: sourceDatabaseRecords.length,
  connectedSources: sourceDatabaseRecords.filter((s) => s.status === "active").length,
  readyToConnectSources: sourceDatabaseRecords.filter((s) => s.status === "ready_to_connect").length,
  manualSubscriptionSources: sourceDatabaseRecords.filter((s) =>
    ["manual_only", "subscription_manual"].includes(s.status),
  ).length,
  restrictedSources: sourceDatabaseRecords.filter((s) => s.status === "restricted").length,
  plannedTrueApis: sourceDatabaseRecords.filter((s) => s.connectorType === "API" && s.status !== "active").length,
  parserCandidates: sourceDatabaseRecords.filter((s) => s.connectorType === "Public Page Parser").length,
};
